# purple = "#9A348E"
# pink = "#DA627D"
# orange = "#FCA17D"
# blue = "#86BBD8"
# green = "#06969A"
# gray = "#33658A"

format = """
[](#9A348E)\
$os\
$username\
$sudo\
$time\
[](bg:#DA627D fg:#9A348E)\
$conda\
$nix_shell\
$docker_context\
$aws\
$kubernetes\
[](fg:#DA627D bg:#86BBD8)\
$git_branch\
$git_status\
[](fg:#86BBD8 bg:#06969A)\
$c\
$golang\
$python\
$nodejs\
$rust\
$helm\
[](fg:#06969A bg:#33658A)\
$directory\
[](fg:#33658A)\
$character
"""

# Disable the blank line at the start of the prompt
#add_newline = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = false
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = true

[sudo]
style = 'bg:#9A348E'
format = '[$symbol]($style)'
disabled = false

[time]
disabled = false
style = "bg:#9A348E"
format = '[$time ]($style)'
time_format = "%R" # Hour:Minute Format

# -------------- contexts ---------------

[conda]
style = "bg:#DA627D"
format = '[ $symbol$environment ]($style)'

[nix_shell]
style = "bg:#DA627D"
format = '[ $symbol$state( \($name\))]($style)'

[docker_context]
symbol = ""
style = "bg:#DA627D"
format = '[ $symbol $context ]($style) $path'

[aws]
symbol = "☁️ "
style = "bg:#DA627D"
format = '[ $symbol($profile)(-$region )]($style)'
disabled = false

[aws.region_aliases]
us-west-2 = 'uw2'
eu-central-1 = 'ec1'

[kubernetes]
symbol = "☁️ "
style = "bg:#DA627D"
format = '[ ($context )]($style)'
disabled = false
contexts = [
    { context_pattern = "arn:aws:eks:.*:cluster/dev", context_alias = "dev" },
    { context_pattern = "arn:aws:eks:.*:cluster/stg", context_alias = "stg" },
    { context_pattern = "arn:aws:eks:.*:cluster/live", context_alias = "live" },
]

# -------------- git ---------------

[git_branch]
symbol = "🌿"
style = "fg:black bg:#86BBD8"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:black bg:#86BBD8"
format = '[$all_status$ahead_behind ]($style)'

# -------------- languages ---------------

[c]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#06969A"
format = '[ ${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'

[scala]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

# -------------- location ---------------

[directory]
style = "bg:#33658A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "
